id: I0F2E6C0D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:50:07+00:00'
last_modified: '2022-06-07T16:40:51.041082+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4931
  title: བློ་གསལ་དགའ་བསྐྱེད་སྙིང་གི་ནོར་བུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3821':
      image_group_id: I1KG5051
      title: ''
      total_pages: 416
      order: 1
      base_file: 3821.txt
    14D5:
      image_group_id: I1KG5052
      title: ''
      total_pages: 398
      order: 2
      base_file: 14D5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
